"""empty message

Revision ID: 409a16977f60
Revises: 05cc9f4dcd5e
Create Date: 2025-09-01 12:06:11.288340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409a16977f60'
down_revision = '05cc9f4dcd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
